name: Update Data Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
   - cron: '20 * * * *' # run every hour after source get's updated

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Data Package
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"  
      - run: make
      - name: push
        uses: actions-x/commit@v2
        with:
          name: GitHub Action Updater
          commit-message: Automatic update of vaccination data
