name: Update Data Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
   - cron: '20 * * * *' # run every hour after source get's updated

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Data Package
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"  
      - run: make
      - name: push
        uses: actions-x/commit@v2
        with:
          name: GitHub Action Updater
          message: Automatic update of vaccination data
  push_to_datahub:
    needs: update
    # if: ${{ github.ref == 'refs/heads/main' && contains('Your branch is up to date', jobs.update.steps[5].outputs) }} 
    runs-on: ubuntu-latest
    name: Push Data Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g data-cli
      - shell: bash
        env:
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }}
          DATAHUB_PROVIDERID: $${{ secrets.DATAHUB_PROVIDERID }}
          DATAHUB_ID: ${{ secrets.DATAHUB_ID }}
          DATAHUB_EMAIL: thorben.westerhuys@gmail.com
          DATAHUB_NAME: Thorben Westerhuys
          DATAHUB_USERNAME: n0rdlicht
        run: |
          mkdir -p .config/datahub
          printf '{"token": "%s","profile": {"email": "%s","id": "%s","name": "%s","provider_id": "%s","username": "%s"}}' "$DATAHUB_TOKEN" "$DATAHUB_EMAIL" "$DATAHUB_ID" "$DATAHUB_NAME" "$DATAHUB_PROVIDERID" "$DATAHUB_USERNAME" > .config/datahub/config.json
          export DATAHUB_JSON=.config/datahub/config.json
          make push
