name: Update Data Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Data Package
    outputs:
      old_sha: ${{ steps.old_sha.outputs.OLD_SHA }}
      new_sha: ${{ steps.new_sha.outputs.NEW_SCHA }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: get old sha
        id: old_sha
        run: |
          sha_old=$(git rev-parse HEAD)
          echo $sha_old
          echo "::set-output name=OLD_SHA::$sha_old"  
      - run: make
      - name: push
        uses: actions-x/commit@v2
        with:
          name: GitHub Action Updater
          message: Automatic update of vaccination data
      - name: get new sha
        id: new_sha
        run: |
          sha_new=$(git rev-parse HEAD)
          echo $sha_new
          echo "::set-output name=NEW_SCHA::$sha_new"
  push_to_datahub:
    needs: update
    if: ${{ github.ref == 'refs/heads/main' && needs.update.outputs.old_sha != needs.update.outputs.new_sha }} 
    runs-on: ubuntu-latest
    name: Push Data Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g data-cli
      - shell: bash
        env:
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }}
          DATAHUB_PROVIDERID: $${{ secrets.DATAHUB_PROVIDERID }}
          DATAHUB_ID: ${{ secrets.DATAHUB_ID }}
          DATAHUB_EMAIL: thorben.westerhuys@gmail.com
          DATAHUB_NAME: Thorben Westerhuys
          DATAHUB_USERNAME: n0rdlicht
        run: |
          mkdir -p .config/datahub
          printf '{"token": "%s","profile": {"email": "%s","id": "%s","name": "%s","provider_id": "%s","username": "%s"}}' "$DATAHUB_TOKEN" "$DATAHUB_EMAIL" "$DATAHUB_ID" "$DATAHUB_NAME" "$DATAHUB_PROVIDERID" "$DATAHUB_USERNAME" > .config/datahub/config.json
          export DATAHUB_JSON=.config/datahub/config.json
          make push
